
build-package:
  stage: deploy
  image: registry.svleddar-gitlab.leddartech.local/devopsadmin/common_docker_images/gcc_cmake_py3:v01.04
  tags:  
    - gcc-cmake-py3-v01.04-mountpoint
  script:
    - export REQUESTS_CA_BUNDLE="/etc/ssl/certs/ca-certificates.crt"
    - cat $PYPIRC > /tmp/.pypirc
    - pip3 install twine
    - pip3 install --upgrade keyrings.alt 
    - python3 setup.py bdist_wheel sdist
    
    - python3 -m twine upload dist/* -u leddartech -p $PYPI_PWD
    - export TWINE_PASSWORD=${CI_JOB_TOKEN}
    - export TWINE_USERNAME=gitlab-ci-token
    - python3 -m twine upload --repository-url https://svleddar-gitlab.leddartech.local/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  only:
    - tags
    
  artifacts:
    paths:
      - build/sphinx/html/*