build-package:
  stage: deploy
  image: python:3.6
  script:
    - cat $PYPIRC > /tmp/.pypirc
    - pip install twine
    - python setup.py bdist_wheel
    - python -m twine upload --repository gitlab dist/leddartech-common-${CI_COMMIT_TAG}-py3-none-any.whl --config-file /tmp/.pypirc
  only:
    - tags